### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by tmcw** [mapbox/tile-stat-stream#5]
@rclark we can deprecate this repo, right, now that tilestats is using a different codebase? Would it be safe to unpublish the module as well?

**Comment by rclark** [comment]
Yeah I believe so, just want to double-check with @davidtheclark?

**Comment by davidtheclark** [comment]
Yep. mapbox-geostats [does not depend on this](https://github.com/mapbox/mapbox-geostats/blob/master/package.json), so I don't know of a reason not to deprecate.

**Comment by tmcw** [comment]
👍 package deprecated
